[build]
  publish = "yasashii-sudoku/public"
  command = "cd exampleSite && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://yasashii-sudoku.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
